"""competency framework and snapshots

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-25
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Seed data is copied here (not imported) so later edits to app/models/seed.py cannot change this migration.
COMPETENCIES = [
    ('technical', 'Technical', 'Applying tools, programming and domain technologies to build working solutions.'),
    ('problem_solving', 'Problem-Solving', 'Analysing problems and designing effective solutions under constraints.'),
    ('communication', 'Communication', 'Explaining ideas clearly in writing, presentations and discussion.'),
    ('leadership', 'Leadership', 'Taking responsibility, guiding others and driving initiatives.'),
    ('collaboration', 'Collaboration', 'Working effectively in teams and with diverse people.'),
    ('creativity', 'Creativity', 'Generating original ideas and novel approaches.'),
    ('research', 'Research', 'Investigating questions systematically and producing new knowledge.'),
    ('continuous_learning', 'Continuous Learning', 'Independently acquiring new knowledge and skills over time.'),
]
# Weights in COMPETENCIES order.
WEIGHTS = {
    'project': (0.9, 0.7, 0.2, 0.2, 0.4, 0.6, 0.3, 0.3),
    'certification': (0.7, 0.2, 0.0, 0.0, 0.0, 0.0, 0.1, 0.9),
    'online_course': (0.6, 0.2, 0.0, 0.0, 0.0, 0.1, 0.1, 0.8),
    'hackathon': (0.7, 0.9, 0.3, 0.3, 0.8, 0.8, 0.1, 0.3),
    'competition': (0.5, 0.9, 0.2, 0.1, 0.2, 0.4, 0.1, 0.3),
    'workshop': (0.4, 0.2, 0.2, 0.0, 0.3, 0.2, 0.2, 0.7),
    'internship': (0.8, 0.6, 0.6, 0.3, 0.7, 0.3, 0.3, 0.5),
    'paper': (0.5, 0.5, 0.6, 0.1, 0.3, 0.4, 1.0, 0.4),
    'club_role': (0.1, 0.3, 0.7, 0.9, 0.7, 0.3, 0.0, 0.2),
    'event_organizing': (0.1, 0.4, 0.7, 0.7, 0.8, 0.4, 0.0, 0.1),
    'volunteering': (0.0, 0.2, 0.6, 0.3, 0.8, 0.2, 0.0, 0.2),
    'award': (0.4, 0.4, 0.2, 0.3, 0.2, 0.3, 0.3, 0.3),
}  # fmt: skip


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    competencies = op.create_table('competencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('competency_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('scores', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('trigger', sa.String(length=30), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competency_snapshots_taken_at'), 'competency_snapshots', ['taken_at'], unique=False)
    op.create_index(op.f('ix_competency_snapshots_user_id'), 'competency_snapshots', ['user_id'], unique=False)
    op.create_table('mapping_weights',
    sa.Column('activity_type_id', sa.Integer(), nullable=False),
    sa.Column('competency_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['activity_type_id'], ['activity_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('activity_type_id', 'competency_id')
    )
    op.add_column('users', sa.Column('synthetic_persona', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_users_synthetic_persona'), 'users', ['synthetic_persona'], unique=False)
    # ### end Alembic commands ###

    op.bulk_insert(
        competencies,
        [{"key": k, "label": label, "description": d, "sort_order": i} for i, (k, label, d) in enumerate(COMPETENCIES)],
    )
    conn = op.get_bind()
    type_ids = dict(conn.execute(sa.text("SELECT key, id FROM activity_types")).all())
    comp_ids = dict(conn.execute(sa.text("SELECT key, id FROM competencies")).all())
    rows = [
        {"activity_type_id": type_ids[t], "competency_id": comp_ids[c[0]], "weight": w}
        for t, ws in WEIGHTS.items()
        if t in type_ids
        for c, w in zip(COMPETENCIES, ws, strict=True)
    ]
    op.bulk_insert(sa.table("mapping_weights", sa.column("activity_type_id"), sa.column("competency_id"), sa.column("weight")), rows)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_synthetic_persona'), table_name='users')
    op.drop_column('users', 'synthetic_persona')
    op.drop_table('mapping_weights')
    op.drop_index(op.f('ix_competency_snapshots_user_id'), table_name='competency_snapshots')
    op.drop_index(op.f('ix_competency_snapshots_taken_at'), table_name='competency_snapshots')
    op.drop_table('competency_snapshots')
    op.drop_table('competencies')
    # ### end Alembic commands ###
